### ISSUE TITLE
Example code fails - ValueError: could not convert string to float: 'amount-of-money'

### ISSUE THREAD

**Issue by hasansalimkanmaz** [duckling-python-wrapper/fb_duckling#11]
After installing the fb_duckling as stated in readme.md. I couldn't run example code that is also in readme.md.

    from fb_duckling import Duckling
    duckling = Duckling(locale="en_US")

Here is the traceback

    Traceback (most recent call last):
      File "<input>", line 2, in <module>
      File "/Users/........./python3.7/site-packages/fb_duckling/duckling.py", line 30, in __init__
        self.dim_onh.fit(np.array(self.dim_list).reshape(-1, 1))
      File "/Users/......../python3.7/site-packages/sklearn/preprocessing/data.py", line 1956, in fit
        self.fit_transform(X)
      File "/Users/......../python3.7/site-packages/sklearn/preprocessing/data.py", line 2019, in fit_transform
        self.categorical_features, copy=True)
      File "/Users/......../python3.7/site-packages/sklearn/preprocessing/data.py", line 1809, in _transform_selected
        X = check_array(X, accept_sparse='csc', copy=copy, dtype=FLOAT_DTYPES)
      File "/Users/........./python3.7/site-packages/sklearn/utils/validation.py", line 433, in check_array
        array = np.array(array, dtype=dtype, order=order, copy=copy)
    ValueError: could not convert string to float: 'amount-of-money'

**Comment by hasansalimkanmaz** [comment]
After upgrading scikit-learn 0.19.2 -> 0.23.2. It is solved.
